--
-- PostgreSQL database dump
--

\restrict edbjhuMtXIuCoQAxQ5cxbEILCVuEf0aO8BAG3VtKDcfP58Ksaznny2n3ptbBQkW

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.6 (Debian 17.6-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: guardian; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guardian (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    type text,
    family_id bigint,
    first_name text,
    last_name text,
    email character varying,
    phone_number text,
    address_1 text,
    address_2 text,
    city text,
    state text,
    zip text,
    email_norm text GENERATED ALWAYS AS (lower((COALESCE(email, ''::character varying))::text)) STORED,
    dob date,
    race_ethnicity jsonb,
    why_need_child_care jsonb
);


--
-- Name: Guardian_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guardian ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Guardian_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: child; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.child (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    family_id bigint,
    first_name text,
    middle_name text,
    last_name text,
    dob date,
    monthly_allocation numeric DEFAULT '0'::numeric NOT NULL,
    prorated_allocation numeric DEFAULT '0'::numeric NOT NULL,
    status public."Status" DEFAULT 'Pending'::public."Status" NOT NULL,
    payment_enabled boolean DEFAULT false NOT NULL,
    guardian_name text,
    provider_name text,
    wishlist boolean,
    first_name_norm text GENERATED ALWAYS AS (lower(COALESCE(first_name, ''::text))) STORED,
    last_name_norm text GENERATED ALWAYS AS (lower(COALESCE(last_name, ''::text))) STORED,
    race_ethnicity jsonb,
    current_care jsonb,
    language jsonb
);


--
-- Name: child_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.child ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.child_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: family; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.family (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    referred_by character varying,
    size numeric,
    yearly_income numeric,
    zip text,
    approved date,
    language text NOT NULL,
    waitlist boolean,
    submission_id text
);


--
-- Name: family_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.family ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.family_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provider; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    address_1 text,
    address_2 text,
    city text,
    state text,
    zip text,
    licensed boolean,
    license_number character varying,
    license_name character varying,
    license_type character varying,
    first_name text,
    last_name text,
    email text,
    phone character varying,
    care_location_address_1 character varying,
    care_location_address_2 character varying,
    care_location_city text,
    care_location_state text,
    care_location_zip text,
    ssn_or_itin boolean,
    care_setting text,
    related_to_some_children boolean,
    related_to_relationship text,
    related_to_all_children boolean,
    number_of_children numeric,
    children_under_2 numeric,
    cpr_certified text,
    other_adults jsonb,
    pay_types jsonb,
    pay_rate character varying,
    pay_per_month numeric,
    satisfaction_current_pay text,
    satisfaction_current_experience text,
    satisfaction_current_experience_explanation character varying,
    "monthly_rate_0-18" character varying,
    "monthly_rate_19-36" character varying,
    accepted_forms_of_payment jsonb,
    attendance_tracking_system jsonb,
    when_families_pay text,
    w9 text[],
    cpr_upload text[],
    link_id text,
    referrer_cap_family text,
    preferred_language text,
    status public."Status" DEFAULT 'Pending'::public."Status" NOT NULL,
    type public."Provider Type",
    payment_enabled boolean DEFAULT false NOT NULL,
    approved boolean,
    waitlist boolean,
    approved_at timestamp with time zone,
    cpr_training_link text,
    child_safety_module_training_completed_at timestamp with time zone,
    safe_sleep_for_infants_training_completed_at timestamp with time zone,
    home_safety_and_injury_prevention_training_completed_at timestamp with time zone,
    cpr_online_training_completed_at timestamp with time zone,
    background_check_links text[]
);


--
-- Name: COLUMN provider.cpr_training_link; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.provider.cpr_training_link IS 'Unique link to CPR training';


--
-- Name: COLUMN provider.child_safety_module_training_completed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.provider.child_safety_module_training_completed_at IS 'Date/time uses mark that they have completed  https://headstart.gov/safety-practices/article/child-safety';


--
-- Name: COLUMN provider.safe_sleep_for_infants_training_completed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.provider.safe_sleep_for_infants_training_completed_at IS 'Date/time user marked Safe Sleep for infants training as completed';


--
-- Name: COLUMN provider.home_safety_and_injury_prevention_training_completed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.provider.home_safety_and_injury_prevention_training_completed_at IS 'Date/Time user marked Home Safety and Injury Prevention as completed';


--
-- Name: provider_child_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_child_mapping (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    child_id bigint NOT NULL,
    provider_id bigint NOT NULL
);


--
-- Name: provider_child_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provider_child_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_child_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provider_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- PostgreSQL database dump complete
--

\unrestrict edbjhuMtXIuCoQAxQ5cxbEILCVuEf0aO8BAG3VtKDcfP58Ksaznny2n3ptbBQkW

